M48
; DRILL file {KiCad 9.0.7} date 2026-02-23T21:12:02+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-23T21:12:02+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C5.300
%
G90
G05
T1
X49.05Y-19.223
X122.0Y-106.5
T2
X17.75Y-17.672
X17.75Y-192.0
X122.15Y-17.922
X125.0Y-192.0
M30
